=head1 NAME

apid example usage

=head1 DESCRIPTION

This is a simple API interface to a hosts processes. It uses
B<apid> and C<ps>. It consits of two parts, the apid uri map
B<ps.pm> and a client interface B<index.html> which uses
Jquery to access the interface.

=head1 USAGE

Once apid is installed, start the server like this:

 cd sample/
 apid -c ps.conf -f start

Then point your browser to L<http://localhost:8080/>. The
uri / will be served with the mentioned index.html. A process
listing should appear immediately. You can click on a process
to see more details and you can search for processes.

=head1 INTERNALS

The uri map uses authentication for some uris (basic authentication),
which is transparent if you access it via index.html. The jquery
script authenticates to the api with the first request. Since apid
returns a session cookie, subsequent requests don't require additional
measures.

=head1 SECURITY

Please don't run this example on an internet facing server. It displays 
all processes which is dangerous if third parties can view them.

=head1 SEE ALSO

L<HTTP::Daemon::APID>

=head1 AUTHOR

T.v.Dein <tlinden@cpan.org>

=head1 COPYRIGHT

Copyright (c) 2014 by T.v.Dein <tlinden@cpan.org>.
All rights reserved.

=head1 LICENSE

This program is free software; you can redistribute it
and/or modify it under the same terms as Perl itself.

=cut

